### ISSUE TITLE
How to handle "No controller bound" error with a default 404 response?

### ISSUE THREAD

**Issue by NeiAozora** [tnapf/Router#18]
Is it possible to configure a default 404 response when the routing encounters a "No controller bound" error for an invalid URL that is not defined in the routes?

Error Message:
``[2023-06-28T06:15:06.832810+02:00] http.ERROR: Tnapf\Router\Exceptions\HttpNotFound: No controller bound to /invalid-site``

**Comment by CommandString** [comment]
Yes this indeed is a way. You have to create a catcher for this exception

```php
use Tnapf\Router\Exceptions\HttpNotFound;
use Tnapf\Router\Routing\RouteRunner;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;

$router->catch(
  HttpNotFound::class,
  static function (
    ServerRequestInterface $request,
    ResponseInterface $response,
    RouteRunner $route
  ) {
    $response->getBody()->write("{$request->getUri()->getPath()} does not exist");
    return $response;
  }
);
```

You can refer to the [catching](https://github.com/tnapf/Router#catching) section of the documentation
